import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { CommandMenuProvider } from "@/components/CommandMenuContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="antialiased scroll-smooth">
      <body
        className={`${GeistSans.className} bg-zinc-100 dark:bg-zinc-900 selection:bg-zinc-400/25 dark:selection:bg-zinc-600/25 relative`}
      >
        <CommandMenuProvider>
          {children}
        </CommandMenuProvider>
      </body>
    </html>
  );
}
